Gymsolutions/Controllers/RoutinesController.cs
using GymSolutions.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymSolutions.Controllers
{
    public class RoutinesController : Controller
    {
        GymSolutionEntities1 contexto = new GymSolutionEntities1();


        // GET: Routines
        public ActionResult Index()
        {
            var rutinas = contexto.Rutina.ToList();

            return View(rutinas);
        }

        public ActionResult VerRutina()
        {
            return View();
        }

        public ActionResult NuevaRutina( int ejer = 1)
        {
            

            return View();
        }

        public ActionResult EditarRutina()
        {
            return View();
        }

    }
}

Gymsolutions/Views/Routines/Index.cshtml
@model List<GymSolutions.Models.Rutina>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/Content/rutinaIndex.css" rel="stylesheet" />
</head>
<body>
    <h1 align="center">Rutinas</h1>
    <div class="row">
        <div class="col-lg-2">
            @Html.ActionLink("Crear rutina", "NuevaRutina", "Routines", new { @class = "btn btn-lg btn-success" })
        </div>
    </div>

    <div class="row" id="ejercicios-row">
        <div id="pechoRow">
            @foreach (GymSolutions.Models.Rutina item in Model) { 
            <div class="col-lg-4">
                <div class="panel panel-info">
                    <div class="panel-heading">@item.rutNombre</div>
                    <div class="panel-body">@item.rutFechaCreacion</div>
                    <div class="panel-body row">
                        <div class="col-lg-4 col-sm-12" align="center"> @Html.ActionLink("Ver", "VerRutina", "Routines", new { @class = "btn btn-primary" })</div>
                        <div class="col-lg-4 col-sm-12" align="center"> @Html.ActionLink("Editar", "EditarRutina", "Routines", new { @class = "btn btn-primary" })</div>
                        <div class="col-lg-4 col-sm-12" align="center"><btn class="btn btn-danger">Eliminar</btn></div>
                    </div>
                </div>

            </div>
            }
        </div>
    </div>

</body>